server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy → booking-service  (/api/bookings  in  /api/bookings/...)
    location /api/bookings {
        rewrite ^/api/bookings(.*)$ /bookings$1 break;
        proxy_pass http://booking-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → user-service  (/api/users  in  /api/users/...)
    location /api/users {
        rewrite ^/api/users(.*)$ /users$1 break;
        proxy_pass http://user-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Health check booking-service
    location /api/health {
        proxy_pass http://booking-service:3001/health;
    }

    # Statične datoteke
    location / {
        try_files $uri $uri/ /index.html;
    }
}
