name: Web UI CI

on:
  push:
    paths:
      - "web-ui/**"
  pull_request:
    paths:
      - "web-ui/**"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-ui
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web-ui:${{ github.sha }}
